### ISSUE TITLE
enhancement: Improve breath while submerged

### ISSUE THREAD

**Issue by ApolloX939** [APercy/nautilus#8]
Currently the submarine will always set the breath to 10 (which is fine in normal scenarios), but could it instead set it to the maximum value...

[Upgrade Packs](https://content.minetest.net/packages/Krock/upgrade_packs/) for instance could increase breath by 10 or more thus doubling the maximum that the submarine doesn't use.

## How

```lua
-- Taken from Rebreather (MIT License)
-- api.lua (Starting from line 62)
local air = player:get_breath()
local props = player:get_properties()
local max_air = props.breath_max
-- ... (Useless code that you probably don't want, or maybe you do, it's there in Rebreather)
player:set_breath(max_air-1) -- -1 so it doesn't make the air bubbles disappear and reappear (can be quite annoying)
```

[Rebreather](https://content.minetest.net/packages/ApolloX/rebreather/)

## Why

- The submarine will supply the pilot with air and fully make use of their maximum air capacity (regardless how much that could be)
- If the pilot wanted to get out and mine for example, they could use the submarine to resupply their breath then exit without being so limited to partial of their maximum air capacity

**Comment by APercy** [comment]
done
